name: second pipeline

on:
#   workflow_dispatch:
  push:
jobs:
    download:
        runs-on: ubuntu-latest
        steps:
            - name: download
              uses: dawidd6/action-download-artifact@v3
              with:
                workflow: first.yml
                name: artifact
                path: /tmp/
            - name: print
              run: cat /tmp/artifact.txt