name: second pipeline

on:
#   workflow_dispatch:
  push:
jobs:
    download:
        runs-on: ubuntu-latest
        steps:
            - name: download
              run: |
                curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/mehrdad-ordobadi/testing-artifacts/actions/artifacts/artifact
            - name: print
              run: | 
                ls
                # unzip artifact
                # cat artifact.txt
                