name: second pipeline

on:
#   workflow_dispatch:
  push:
jobs:
    download:
        runs-on: ubuntu-latest
        steps:
            - name: download
              id: download-artifact
              uses: Legit-Labs/action-download-artifact@v2
              with:
                workflow: first.yml
                name: artifact
                path: /tmp/
            - name: print
              run: cat /tmp/artifact.txt